;;======================================================================================================================
;;///// core.inc /////////////////////////////////////////////////////////////////////////////////////////// GPLv2 /////
;;======================================================================================================================
;; (c) 2011 Ostin project <http://ostin.googlecode.com/>
;;======================================================================================================================
;; This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
;; License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later
;; version.
;;
;; This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
;; warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License along with this program. If not, see
;; <http://www.gnu.org/licenses/>.
;;======================================================================================================================

include "conf_lib.asm"
include "dll.asm"
include "exports.inc"
include "ext_lib.asm"
include "fpu.asm"
include "heap.asm"
include "malloc.asm"
include "memory.asm"
include "peload.asm"
include "sched.asm"
include "string.asm"
include "sys.asm"
include "syscall.asm"
include "taskman.asm"
include "thread.asm"
include "v86.asm"
